# SwiftLint Configuration for MacML
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - .build
  - DerivedData
  - Packages

# Disabled rules - these are either too noisy or conflict with SwiftUI patterns
disabled_rules:
  - trailing_whitespace
  - todo
  - opening_brace
  - multiple_closures_with_trailing_closure  # Common SwiftUI pattern
  - empty_count  # Opt-in rule causing issues
  - shorthand_operator  # Can reduce readability in some cases

# Opt-in rules - enable gradually as codebase improves
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - last_where
  - reduce_into
  - sorted_first_last
  - toggle_bool
  - yoda_condition

# Rule configurations - relaxed thresholds for existing codebase
line_length:
  warning: 180
  error: 250
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 800
  error: 1500
  ignore_comment_only_lines: true

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 8
  error: 10

cyclomatic_complexity:
  warning: 20
  error: 30

nesting:
  type_level:
    warning: 4
  function_level:
    warning: 6

identifier_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - ok
    - lhs
    - rhs
    - lr
    - db
    - tp
    - fp
    - fn
    - t   # table definition in GRDB
    - r   # color components
    - g
    - b
    - v   # value in loops
    - w   # width
    - h   # height
    - s   # string/size
    - p   # point/precision
    - q   # query
    - f   # f1-score
    - m   # model/metrics

large_tuple:
  warning: 5
  error: 6

type_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80

# Custom rules
custom_rules:
  no_print_in_production:
    name: "No print() in production code"
    regex: '^\s*print\s*\('
    match_kinds:
      - identifier
    message: "Use Logger instead of print() for production code"
    severity: warning

  force_cast_suggestion:
    name: "Force cast warning"
    regex: ' as! '
    message: "Force casting is dangerous. Consider using 'as?' with proper error handling."
    severity: warning
